import { z } from "zod";

export const equipmentSchema = z.object({
    id: z.string().uuid().default(() => crypto.randomUUID()),
    name: z.string().min(1, "Name is required"),
    notes: z.string().optional(),
});

export const locationSchema = z.object({
    id: z.string().default(() => crypto.randomUUID()),
    name: z.string().min(1, "Location name is required"),
    description: z.string().optional(),
    imageUrl: z.string().optional(),
    equipment: z.array(equipmentSchema).default([]),
    createdAt: z.date().default(() => new Date()),
});

export const workoutSchema = z.object({
    id: z.string().uuid().default(() => crypto.randomUUID()),
    title: z.string().min(1, "Title is required"),
    content: z.string(), // Markdown content generated by LLM
    locationId: z.string(),
    createdAt: z.date().default(() => new Date()),
});

export type Equipment = z.infer<typeof equipmentSchema>;
export type Location = z.infer<typeof locationSchema>;
export type Workout = z.infer<typeof workoutSchema>;
